name: Doxygen

on:
  push:
    branches:
      - team/dopalacze

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - uses: actions/checkout@v2

    - name: Install Doxygen
      run: |
        sudo apt-get install doxygen
        rm docs/html -rf
        mkdir docs/html

    - name: Generate Doxygen
      run: doxygen docs/Doxyfile

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: docs/html