name: Generate Doxygen

on:
  push:
    branches:
      - team_ghc_ca  # or replace with your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Doxygen
      run: sudo apt-get install doxygen

    - name: Generate Doxygen HTML
      run: doxygen Doxyfile

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: team_ghc-ca
        folder: doc/html  # or replace with the directory where your HTML files are generated
        token: ${{ secrets.GH_TOKEN }}
