name: Deploy GitHub Pages

on:
    push:
        branches: 
            - "gh-pages-*"

jobs:
    # Deploy job
    deploy:
        # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
        permissions:
            pages: write      # to deploy to Pages
            id-token: write   # to verify the deployment originates from an appropriate source

        # Deploy to the github-pages environment
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        # Specify runner + deployment step
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4.1.5

        # Upload the generated documentation to the artifact store
        - name: Upload Doxygen Documentation
          uses: actions/upload-pages-artifact@v3.0.1
          with:
            path: html

        # Deploy the documentation to GitHub Pages
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
