name: Generate and Deploy Doxygen Documentation

on:
    push:
        branches: 
            - "master"
            - "team/**"
    pull_request:
        branches: [ "master" ]

jobs:
    # Build job
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4.1.5

        # Generate Doxygen documentation
        - name: Generate Doxygen Documentation
          uses: mattnotmitt/doxygen-action@v1.9.5

        # Push the generated documentation to the gh-pages-CodeAvengers branch
        - name: Push to gh-pages-CodeAvengers
          uses: JamesIves/github-pages-deploy-action@4.1.5
          with:
            branch: gh-pages-CodeAvengers
            folder: html
            target-folder: html

    # Deploy job
    deploy:
        # Add a dependency to the build job
        needs: build

        # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
        permissions:
            pages: write      # to deploy to Pages
            id-token: write   # to verify the deployment originates from an appropriate source

        # Deploy to the github-pages environment
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        # Specify runner + deployment step
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4.1.5
          with:
            ref: gh-pages-CodeAvengers

        # Upload the generated documentation to the artifact store
        - name: Upload Doxygen Documentation
          uses: actions/upload-pages-artifact@v3.0.1
          with:
            path: html

        # Deploy the documentation to GitHub Pages
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
